SAILearningWeb/SAILearningWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('perfiles.urls', namespace='perfiles')),
    path('niveles/', include('levels.urls', namespace='levels'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAILearningWeb/levels/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'levels'

urlpatterns = [
    path('', views.avance, name='avance'),
    path('nivel/<int:nivel>/', views.nivel, name='level'),
    path('nivel/<int:nivel>/', views.nivel_2, name='nivel2'),
]

SAILearningWeb/perfiles/urls.py
from django.urls import path
from . import views

app_name = 'perfiles'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.loginPage, name='login'),
    path('', views.home, name='home'),
    path('logout/', views.logout_view, name='logout'),
]

SAILearningWeb/levels/models.py
from django.db import models

# Create your models here.

SAILearningWeb/perfiles/models.py
from django.db import models
from django.contrib.auth.models import User

User._meta.get_field('email').blank = False

class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    nivel = models.IntegerField(default=1)
    #imagen = models.ImageField(upload_to='perfiles/', default='perfiles/default.jpg')

    def __str__(self):
        return self.usuario.username
    
    class Meta:
        verbose_name_plural = "Perfiles"

SAILearningWeb/perfiles/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Perfil

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña'}))
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirma la contraseña'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Nombre de usuario'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Correo electrónico'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password != password_confirm:
            raise forms.ValidationError("Las contraseñas no coinciden")

        return cleaned_data

SAILearningWeb/levels/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from perfiles.models import Perfil

@login_required(login_url="/login/")
def avance(request):
    user = request.user
    perfil = Perfil.objects.get(usuario=user)
    niveles = range(1, 61)  # Crea una lista de niveles del 1 al 30
    nivel_actual = request.user.perfil.nivel  # Obtiene el nivel actual del usuario
    context = {
        'niveles': niveles,
        'nivel_actual': nivel_actual,
        'user':user, 
        'perfil':perfil
    }
    return render(request, 'levels/app.html', context=context)


@login_required

@login_required(login_url="/login/")
def nivel(request, nivel):
    user = request.user
    perfil = request.user.perfil
    niveles = range(1, 61)  # Crea una lista de niveles del 1 al 60
    nivel_actual = nivel

    def actualizar_nivel():
        perfil.nivel = nivel  # Incrementar el nivel del jugador
        perfil.save()  # Guardar los cambios en la base de datos
        return redirect('levels:level', nivel=perfil.nivel)  # Redirigir a la vista del nuevo nivel
    
    if perfil.nivel < nivel:
        actualizar_nivel()

    return render(request, 'levels/level.html', {'nivel_actual': nivel_actual, 'user': user, 'perfil':perfil, 'niveles':niveles})


@login_required(login_url="/login/")
def nivel_2(request, nivel):
    user = request.user
    perfil = request.user.perfil

    perfil.nivel += 1  # Incrementar el nivel del jugador
    perfil.save()  # Guardar los cambios en la base de datos
  
    return render(request, 'levels/level_2.html', {'nivel': nivel, 'user': user, 'perfil':perfil})

SAILearningWeb/perfiles/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import UserRegistrationForm
from django.contrib.auth import logout

def home(request):  
    return render(request, 'perfiles/index.html')

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('perfiles:home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("perfiles:home")  # Redirect to a 'home' page or another relevant page
        else:
            messages.error(request, 'Correo o contraseña no válidos. Vuelve a intentarlo.')

    return render(request, 'perfiles/login.html')

# def logoutUser(request):
#     logout(request)
#     return HttpResponse("Cerraste sesión")

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)

        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password'])
            user.save()

            login(request, user)
            return redirect('perfiles:home') 

        else:
            messages.error(request, 'Error al crear la cuenta. Por favor, vuelve a intentarlo.')
    else:
        user_form = UserRegistrationForm()

    context = {
        'user_form': user_form
    }
    return render(request, 'perfiles/register.html', context)


def logout_view(request):
    logout(request)
    return redirect('perfiles:home')  # Redirect to a 'home' page or another relevant page

SAILearningWeb/levels/templates/levels/app.html
<!DOCTYPE html>
<html lang="es">
  {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SAILearn</title>
    <link rel="stylesheet" href="{% static 'app.css' %}">
    <link rel="stylesheet" href="https://use.typekit.net/ouq2fal.css">
</head>

<body>

    <header>

      <a class="header-logo">
        <span class="bold">SAI</span>Learning
      </a>


      <a class="header-dropdown" onclick="myFunctin()">
        <span class="user-info">{{user.username|title}}<br>Nivel {{perfil.nivel}}</span>
        <img src="{% static 'images/Asset 26@4x.png' %}" class="profile-picture">
        <div class="dropdownLink" id="ddl">
          <a class="dropdownLink-button" onclick="redirectLogout()">Cerrar sesión</a>
        </div>
      </a>
    </header>

    <script src="{% static 'app.js' %}"></script>

    <main>

      <div class="horizontal-scroll-wrapper squares">
        {% for nivel in niveles %}
          {% if nivel <= nivel_actual %}
              {% if nivel == nivel_actual %}
                  <a class="select" href="{% url 'levels:level' nivel %}">{{ nivel }}</a>
              {% else %}
                  <a class="active" href="{% url 'levels:level' nivel %}">{{ nivel }}</a>
              {% endif %}
          {% else %}
              <a>{{ nivel }}</a>
          {% endif %}
{% endfor %}
      </div>

      <a class="btn-startLevel" href="https://google.com">
        <span>¡Continúa aprendiendo!</span>
      </a>
    </main>
      
</body>
</html>

SAILearningWeb/levels/templates/levels/level.html
<!-- https://www.kirupa.com/html5/accessing_your_webcam_in_html5.html -->

<!DOCTYPE html>
<html>
    {% load static %}
<head>
    <meta charset="utf-8">
    <title>Display Webcam Stream</title>
    <link rel="stylesheet" href="{% static 'level.css' %}">
</head>
 
<body>
    <header>

        <div class="header-logo">
            <span class="bold">SAI</span>Learning
        </div>

        <h1>Nivel {{nivel_actual}}</h1>

        <a class="header-dropdown" onclick="myFunctin()">
            <span class="user-info">{{user.username|title}}<br>Nivel {{perfil.nivel}}</span>
            <img href="{% static 'images/Asset 26@4x.png' %}" class="profile-picture">
            <div class="dropdownLink" id="ddl">
                <!-- <a>Perfil</a>
                <a>Glosario</a> -->
                <a class="dropdownLink-button" onclick="redirectLogout()">Cerrar sesión</a>
            </div>
        </a>

      </header>
    <main>

            <div class="left-container">
                <div class="muestra">Muestra la letra</div>
                <img src="{% static '/images/letrasLSM/letra_b.png' %}" class="letras">
            </div>

            <div id="container">
                <video autoplay="true" id="videoElement" style="transform: scaleX(-1)">
                    Your browser does not support the video tag.
                </video>
                <canvas id="canvas" style="display:none;"></canvas>
                <h3 id="detectador">Actualmente detectando: --</h3>
            </div>

            <div class="right-container">
                <div class="semaforo"></div>
                
                <div class="semaforo"></div> 
                
                <div class="semaforo"></div> 
                
                <div class="semaforo"></div>
                
                <div class="semaforo"></div>         
        </div>

    </main>
    <script src="{% static 'level.js' %}"></script>
</body>
</html>

SAILearningWeb/levels/templates/levels/level_2.html
<!-- https://www.kirupa.com/html5/accessing_your_webcam_in_html5.html -->

<!DOCTYPE html>
<html>
    {% load static %}
<head>
    <meta charset="utf-8">
    <title>Display Webcam Stream</title>
    <link rel="stylesheet" href="{% static 'level.css' %}">
</head>
 
<body>
    <header>

        <div class="header-logo">
            <span class="bold">SAI</span>Learning
        </div>

        <h1>Nivel {{perfil.nivel}}</h1>

        <a class="header-dropdown" onclick="myFunctin()">
            <span class="user-info">{{user.username|title}}<br>Nivel {{perfil.nivel}}</span>
            <img href="{% static 'images/Asset 26@4x.png' %}" class="profile-picture">
            <div class="dropdownLink" id="ddl">
                <a>Perfil</a>
                <a>Glosario</a>
                <a>Cerrar Sesión</a>
            </div>
        </a>

      </header>
    <main>

            <div class="left-container">
                <div class="muestra">Muestra la letra</div>
                <img src="{% static '/images/letrasLSM/letra_b.png' %}" class="letras">
            </div>

            <div id="container">
                <video autoplay="true" id="videoElement" style="transform: scaleX(-1)">
                    Your browser does not support the video tag.
                </video>
                <canvas id="canvas" style="display:none;"></canvas>
                <h3 id="detectador">Actualmente detectando: --</h3>
            </div>

            <div class="right-container">
                <div class="semaforo"></div>
                
                <div class="semaforo"></div> 
                
                <div class="semaforo"></div> 
                
                <div class="semaforo"></div>
                
                <div class="semaforo"></div>         
        </div>

    </main>

    <script src="{% static 'level.js' %}"></script>
</body>
</html>

SAILearningWeb/perfiles/templates/perfiles/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SAI Learn</title>
    <link rel="stylesheet" href="{% static 'index.css' %}">
  </head>
  <body>
    <menu>
        <!-- img src="{% static 'images/logo.jpg' %}"-->
        <div class="header-logo-container">
          <img src="{% static 'images/Asset 26@4x.png' %}" class="logo">
          <div><span style="font-weight: 700;">SAI</span>Learning</div>
        </div>
        <button type="button" onclick="redirectToLogin()"><a>Comienza aquí</a></button>
    </menu>
    <main>
      <div class="banner">
        <div>
          <h1>Aprende lengua de señas</h1>
          <p>Utilizando el poder de inteligencia artificial. Rápido. Interactivo. Sencillo.</p>
        </div>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/E85Em8CPPvk?si=MKKfnWVXelhYKOtc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
    <div>
      <div class="info">
        <h2>¿Cómo funciona?</h2>
        <p>
          SAI Learning es una plataforma de aprendizaje de lengua de señas
          que utiliza inteligencia artificial para enseñarte de manera rápida
          y sencilla. Solo necesitas una cámara y conexión a internet.
        </p>
      </div>
      <!--<div class="steps">
        <div class="step">
          <img>
        </div>
      </div>-->
      <div class="info">
        <h2>¿Por qué aprender lengua de señas?</h2>
        <p>
          En méxico más de 2.3 millones de personas padecen una 
          discapacidad auditiva, sin embargo solamente 300 mil personas
          pueden comunicarse físicamente a través de la lengua de señas
          mexicana (LSM) 
          La lengua de señas es un lenguaje visual y gestual utilizado
          por personas con discapacidades auditivas para comunicarse entre
          sí, y con personas oyentes.
          Aprender lengua de señas no solo te permitirá comunicarte con
          este grupo de personas, sino que ayudas a tu comunidad a convertirse
          en un espacio más inclusivo para todas las personas.
        </p>
      </div>
      <div class="info">
        <h2>¿Quiénes somos?</h2>
        <p>
          Somos un equipo de desarrolladores y diseñadores apasionados por la
          tecnología y la inclusión. Creemos en el poder de la tecnología para
          transformar la educación y la accesibilidad, y estamos comprometidos
          en hacer de SAI Learn una plataforma de aprendizaje de lengua de señas
          accesible y efectiva.
        </p>
      </div>
      <div>
        <h2>¿Qué dicen nuestros usuarios?</h2>
        <div class="testimonials">
          <div class="testimonial">
            <img>
            <p>“SAI Learn es una plataforma increíble. Me ha ayudado a aprender lengua de señas de manera rápida y sencilla. ¡Gracias!”</p>
            <span>- María, estudiante</span>
          </div>
          <div class="testimonial">
            <img>
            <p>“SAI Learn es una plataforma increíble. Me ha ayudado a aprender lengua de señas de manera rápida y sencilla. ¡Gracias!”</p>
            <span>- María, estudiante</span>
          </div>
          <div class="testimonial">
            <img>
            <p>“SAI Learn es una plataforma increíble. Me ha ayudado a aprender lengua de señas de manera rápida y sencilla. ¡Gracias!”</p>
            <span>- María, estudiante</span>
          </div>
        </div>
      </div>
      
    </main>
    <footer>
    </footer>

  </body>
</html>

<script>
  function redirectToLogin() {
      window.location.href = "{% url 'levels:avance' %}";
  }
</script>

SAILearningWeb/perfiles/templates/perfiles/login.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SAI Learning</title>
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <link rel="stylesheet" href="https://use.typekit.net/ouq2fal.css">
</head>
<body>
    <header class="App-header">
        <img src="{% static 'images/Asset 7@4x.png' %}" class="chiquito">
    </header>
    <main>
        <div class="register-container">
            <h2>Inicia Sesión</h2>
            <form id="register-form" method="POST" action="{% url 'perfiles:login' %}">
                {% csrf_token %}
                <input type="text" name="username" placeholder="Usuario" required>
                <input type="password" name="password" placeholder="Contraseña" required>
                {% if messages %}
                    <div class="error-message">
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                {% endif %}
                <button type="submit" class="btn-create-account">Iniciar Sesión</button>
                <button type="button" class="btn-existing-account" onclick="redirectToRegister()">Registrarme</button>
            </form>
        </div>
    </main>
</body>
</html>

<script>
    function redirectToRegister() {
        window.location.href = "{% url 'perfiles:register' %}";
    }
</script>

SAILearningWeb/perfiles/templates/perfiles/register.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SAI Learning</title>
    <link rel="stylesheet" href="{% static 'register.css' %}">
    <link rel="stylesheet" href="https://use.typekit.net/ouq2fal.css">
</head>
<body>
    <header class="App-header">
        <img src="{% static 'images/Asset 7@4x.png' %}" class="chiquito">
    </header>
    <main>
        <div class="register-container">
            <h2>¡Regístrate!</h2>
            <form id="register-form" method="POST" action="{% url 'perfiles:register' %}">
                {% csrf_token %}
                {{ user_form.username }} 
                {{ user_form.email }}
                {{ user_form.password }}
                {{ user_form.password_confirm }}
                <div class="error-message">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}    
                </div>
                <small id="password-error" class="error-password" style="display: none; color: red;">Las contraseñas deben de ser iguales</small>
                <button type="button" class="btn-existing-account" onclick="redirectToLogin()">¡Ya tengo cuenta!</button>
                <button type="submit" class="btn-create-account">Crear Cuenta</button>
            </form>
            <p>Al crear una cuenta aceptas nuestros <a href="#">términos y condiciones</a></p>
        </div>
    </main>
    <script>
        function redirectToLogin() {
            window.location.href = "{% url 'perfiles:login' %}";
        }

        document.getElementById('register-form').addEventListener('submit', function(event) {
            const password = document.querySelector('input[name="password"]').value;
            const confirmPassword = document.querySelector('input[name="password_confirm"]').value;

            if (password !== confirmPassword) {
                event.preventDefault();
                document.getElementById('password-error').style.display = 'block';
            } else {
                document.getElementById('password-error').style.display = 'none';
            }
        });
    </script>
</body>
</html>